plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.android_snack'
    compileSdk 35
    // 添加这一行

    defaultConfig {
        applicationId "com.example.android_snack"
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.10.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.activity:activity:1.8.0'

    // 使用 annotationProcessor 或 kapt 来处理 Data Binding 编译器
    annotationProcessor 'androidx.databinding:databinding-compiler:7.4.2'
    // 如果你使用 Kotlin，应该使用 kapt
    // kapt 'androidx.databinding:databinding-compiler:3.2.0-alpha11'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    // 添加本地 JAR 文件
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.squareup.okhttp3:okhttp:4.9.3'
    implementation 'com.google.code.gson:gson:2.8.6'
}